import subprocess
print('Countries')
subprocess.call(['python', 'populate_countries.py'])
print('Genres')
subprocess.call(['python', 'populate_genres.py'])
print('Companies')
subprocess.call(['python', 'populate_companies.py'])
print('People')
subprocess.call(['python', 'populate_people.py'])
print('Movies')
subprocess.call(['python', 'populate_movies.py'])
print('Badges')
subprocess.call(['python', 'populate_badges.py'])
print('News')
subprocess.call(['python', 'cinemablend.py'])
print('Showtimes')
subprocess.call(['python', 'showtimes.py'])