import { getToken } from "./cookies";

export const backend = 'http://localhost:8080'

export const avatars = window.location.origin + "/avatars/"

export const genres = [
  'Action',
  'Adventure',
  'Animation',
  'Comedy',
  'Crime',
  'Documentary',
  'Drama',
  'Family',
  'Fantasy',
  'History',
  'Horror',
  'Music',
  'Mystery',
  'Romance',
  'Science Fiction',
  'TV Movie',
  'Thriller',
  'War',
  'Western',
  'None',
]
export const theaters = {
  "Cinemas NOS Braga Parque": { id: 1, coords: [41.557568, -8.406558] },
  "Cineplace Nova Arcada": { id: 2, coords: [41.578312, -8.430086] },
  "Cinemax Braga": { id: 3, coords: [41.551788, -8.42221] },
  "Cinemax Barcelos": { id: 4, coords: [41.535751, -8.615790] },
  "Fórum Vizela Cinema": { id: 5, coords: [41.378847, -8.311013] },
  "Castello Lopes Espaço Guimarães": { id: 6, coords: [41.509567, -8.238824] },
  "Cinemas NOS Gaia Shopping": { id: 7, coords: [41.117928, -8.622507] },
  "Cinemas NOS Maia Shopping": { id: 8, coords: [41.219235, -8.561404] },
  "Cinemas NOS NorteShopping": { id: 9, coords: [41.181770, -8.654400] },
  "Cinemas NOS Parque Nascente": { id: 10, coords: [41.174301, -8.566650] },
  "Cineplace Mira Maia": { id: 11, coords: [41.255466, -8.653536] },
  "Cinemax Penafiel": { id: 12, coords: [41.207481, -8.278110] },
  "Cinemas NOS Ferrara Plaza": { id: 13, coords: [41.284595, -8.361249] },
  "Cinemas NOS Alameda Shop e Spot": { id: 14, coords: [41.162933, -8.584280] },
  "Cinemas NOS Nosso Shopping": { id: 15, coords: [41.297188, -7.735276] },
  "Cinemas NOS Glicínias": { id: 16, coords: [40.628029, -8.645060] },
  "Cinemas NOS Fórum Viseu": { id: 17, coords: [40.661920, -7.914334] },
  "UCI Arrábida 20": { id: 18, coords: [41.140584, -8.636641] },
  "Cinemas NOS Palácio do Gelo": { id: 19, coords: [40.643717, -7.910701] },
  "Cinemas NOS Alma Shopping Coimbra": { id: 20, coords: [40.204616, -8.407600] },
  "Cinemas NOS Fórum Coimbra": { id: 21, coords: [40.211263, -8.442833] },
  "Cinemas NOS Colombo": { id: 22, coords: [38.755131, -9.187058] },
  "Cinemas NOS Odivelas Strada": { id: 23, coords: [38.782192, -9.191667] },
  "Cinemas NOS Vasco da Gama": { id: 24, coords: [38.768055, -9.097313] },
  "Cinemas NOS Fórum Montijo": { id: 25, coords: [38.695366, -8.942201] },
  "Cinemas NOS Alvaláxia": { id: 26, coords: [38.760989, -9.159871] },
  "Cinemas NOS Almada Fórum": { id: 27, coords: [38.660752, -9.175163] },
  "Cinemas NOS Fórum Algarve": { id: 28, coords: [37.029122, -7.946070] },
  "Cinema City - Leiria": { id: 29, coords: [39.746406, -8.821047] },
  "Cinema City - Campo Pequeno": { id: 30, coords: [38.742346, -9.144920] },
  "UCI El Corte Inglés": { id: 31, coords: [38.732684, -9.153275] },
  "Cinema City - Alegro Alfragide": { id: 32, coords: [38.727603, -9.219050] },
  "Cinebox Cinemas": { id: 33, coords: [39.807080, -7.521982] },
  "Cinemas NOS Algarve Mar Shopping": { id: 34, coords: [37.097494, -7.996047] },
  "Cinema City - Alegro Setúbal": { id: 35, coords: [38.537447, -8.879276] },
  "Cinemas NOS Evora Plaza": { id: 36, coords: [38.549552, -7.905243] },
  "Cineplace AlgarveShopping": { id: 37, coords: [37.127757, -8.279695] }
}


//translations

export const labels = {
  en: {
    //navbar
    news: 'News',
    movies: 'Movies',
    nowPlaying: 'Now Playing',
    people: 'People',
    users: 'Users',
    profile: 'Profile',
    requests: 'Requests',
    logout: 'Logout', 
    //frontpage
    bannerTop: 'ENGAGE WITH YOUR',
    bannerBottom: 'MOVIE FRIENDS!',
    login: 'LOGIN',
    register: 'REGISTER',
    username: 'Username',
    password: 'Password',
    name: 'Name',
    email: 'Email',
    cPassword: 'Confirm Password',
    country: 'Country',
    female: 'Female',
    male: 'Male',
    other: 'Other',
    submit: 'Submit',
    namePattern: 'Name must have between 3 and 50 chars',
    usernamePattern: 'Username must have between 3 and 30 chars',
    passwordPattern: 'Password must have between 8 and 30 chars',
    'User doesn\'t exist': 'User doesn\'t exist',
    'Wrong password': 'Wrong password',
    'Username already registered': 'Username already registered',
    'Email already registered': 'Email already registered',
    newReleases: 'New Releases',
    latestNews: 'Latest News',
    joinMovieverse: 'Join Movieverse Today!',
    sellPoint1: 'Get to know your friends\' movie tastes',
    sellPoint2: 'Catch up with the hottest new releases',
    sellPoint3: 'Keep track of your entire movie history',
    sellPoint4: 'Earn achievements watching movies',
    statistics: 'Statistics',
    members: 'Members',
    comments: 'Comments',
    aboutUs: 'About Us',
    aboutUsText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nec magna lorem. Etiam quis sapien convallis, eleifend arcu vel, euismod tellus. Suspendisse porttitor est nibh, id semper enim eleifend in. Aliquam erat volutpat. Etiam finibus dui sed nunc semper condimentum. Vestibulum quis nulla quis quam pulvinar porttitor. Nullam ut dignissim justo. Aliquam erat volutpat. Etiam finibus dui sed nunc semper condimentum. Vestibulum quis nulla quis quam pulvinar porttitor. Nullam ut dignissim justo. Aliquam erat volutpat. Etiam finibus dui sed nunc semper condimentum. Vestibulum quis nulla quis quam pulvinar porttitor. Nullam ut dignissim justo.',
    //footer
    contactUs: 'Contact Us',
    rightsReserved: '© Movieverse 2019. All rights reserved.',
    //movie search
    movieSearch: 'Movie Search',
    genres: 'Genres',
    sortBy: 'Sort By',
    dateAsc: 'Date (Ascending)',
    dateDesc: 'Date (Descending)',
    rating: 'Rating',
    popular: 'Popular',
    upcoming: 'Upcoming',
    showMore: 'Show More',
    //genres
    Action: '🔥 Action',
    Adventure: '🗺️ Adventure',
    Animation: '🐭 Animation',
    Comedy: '😂 Comedy',
    Crime: '👮 Crime',
    Documentary: '💡 Documentary',
    Drama: '🎭 Drama',
    Family: '👪 Family',
    Fantasy: '🗡️ Fantasy',
    History: '📜 History',
    Horror: '👻 Horror',
    Music: '🎵 Music',
    Mystery: '🕵️‍ Mystery',
    Romance: '❤️ Romance',
    'Science Fiction': '🤖 Science Fiction',
    'TV Movie': '📺 TV Movie',
    Thriller: '🔪 Thriller',
    War: '⚔️ War',
    Western: '🤠 Western',
    None: 'None',
    //showtimes
    showtimes: 'Showtimes',
    noMoviesFound: 'No movies found',
    //people search
    peopleSearch: 'Search Cast and Crew Members',
    bornToday: 'Born Today',
    years: 'years',
    peopleMostCredits: 'People with most credits',
    credits: 'credits',
    //aux pages
    noResultsFound: 'No results found',
    loading: 'Loading',
    noMoreResults: 'No more results',
    toTheMainPage: 'To the main page!',
    pageNotFound: '404 - Page not found',
    noAuth: 'You must be logged in to access this page',
    //profile
    favouriteGenre: 'Favourite Genre',
    birthdate: 'Birthdate',
    joined: 'Joined',
    hours: 'Hours',
    ratings: 'Ratings',
    friends: 'Friends',
    recent: 'Recent',
    favourites: 'Favourites',
    watchlist: 'Watchlist',
    recommended: 'Recommended',
    noFriends: 'No friends',
    confirm: 'Confirm',
    cancel: 'Cancel',
    changeAvatar: 'Change avatar',
    dragImage: 'Drag an image or click here to select',
    //find users
    findUsers: 'Find Users',
    usernameRealName: 'Username/Real Name',
    userMightKnow: 'Users you might know',
    mostUpvoted: 'Most upvoted',
    likes: 'Likes',
    //friends requests
    friendsRequests: 'Friends Requests',
    received: 'Received',
    sent: 'Sent',
    reject: 'Reject',
    rejected: 'Rejected',
    accept: 'Accept',
    accepted: 'Accepted',
    canceled: 'Canceled',
    friendsInCommon: 'friends in common',
    requestFrom: 'Request from',
    requestTo: 'Request to',
    // movie page
    markWatched: 'Mark watched',
    markedWatched: 'Watched!',
    addToFavourites: 'Add to favourites',
    addedToFavourites: 'Added to favourites!',
    addToWatchlist: 'Add to watchlist',
    addedToWatchlist: 'Added to watchlist',
    originalLanguage: 'Original Language',
    runtime: 'Runtime',
    genres: 'Genres',
    prodCompanies: 'Production companies',
    summary: 'Summary',
    cast: 'Cast',
    media: 'Media',
    posters: 'Posters',
    videos: 'Videos',
    backdrops: 'Backdrops',
    discussion: 'Discussion',
    addComment: 'Add comment',
    addCommentPlaceholder: 'Add comment...',
    //admin
    globalStats: 'Global Statistics',
    genders: 'Genders',
    countries: 'Countries',
    timeRange: 'Time Range',
    updateInterval: 'Refresh rate',
    second: 'second',
    seconds: 'seconds',
    minute: 'minute',
    minutes: 'minutes',
    hour: 'hour',
    hours: 'hours',
    day: 'day',
    week: 'week',
    weeks: 'weeks',
    month: 'month',
    months: 'months',
    year: 'year'
  },
  pt: {
    //navbar
    news: 'Notícias',
    movies: 'Filmes',
    nowPlaying: 'Em exibição',
    people: 'Pessoas',
    users: 'Utilizadores',
    profile: 'Perfil',
    requests: 'Pedidos',
    logout: 'Sair', 
    //frontpage
    bannerTop: 'INTERAGE COM OS TEUS',
    bannerBottom: 'AMIGOS DE CINEMA!',
    login: 'LOGIN',
    register: 'REGISTAR',
    username: 'Nome de utilizador',
    password: 'Palavra-pass',
    name: 'Nome',
    email: 'Email',
    cPassword: 'Confirmar palavra-pass',
    country: 'País',
    female: 'Feminino',
    male: 'Masculino',
    other: 'Outro',
    submit: 'Submeter',
    namePattern: 'Nome tem que ter entre 3 e 50 carateres',
    usernamePattern: 'Nome de utilizador tem que ter entre 3 e 30 carateres',
    passwordPattern: 'Palavra-pass tem que ter entre 8 e 30 carateres',
    passwordMatch: 'Palavras-pass têm que ser iguais',
    'User doesn\'t exist': 'Utilizador não existe', 
    'Wrong password': 'Palavra-pass incorreta',
    'Username already registered': 'Nome de u. já registado',
    'Email already registered': 'Email já registado',
    newReleases: 'Novas estreias',
    latestNews: 'Últimas Notícias',
    joinMovieverse: 'Junta-te hoje ao Movieverse!',
    sellPoint1: 'Fica a conhecer os gostos cinemáticos dos teus amigos',
    sellPoint2: 'Não percas as últimas novidades',
    sellPoint3: 'Mantém-te a par do teu histórico cinemático',
    sellPoint4: 'Desbloqueia conquistas ao ver filmes',
    statistics: 'Estatísticas',
    members: 'Membros',
    comments: 'Comentários',
    aboutUs: 'Sobre Nós',
    aboutUsText: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur nec magna lorem. Etiam quis sapien convallis, eleifend arcu vel, euismod tellus. Suspendisse porttitor est nibh, id semper enim eleifend in. Aliquam erat volutpat. Etiam finibus dui sed nunc semper condimentum. Vestibulum quis nulla quis quam pulvinar porttitor. Nullam ut dignissim justo. Aliquam erat volutpat. Etiam finibus dui sed nunc semper condimentum. Vestibulum quis nulla quis quam pulvinar porttitor. Nullam ut dignissim justo. Aliquam erat volutpat. Etiam finibus dui sed nunc semper condimentum. Vestibulum quis nulla quis quam pulvinar porttitor. Nullam ut dignissim justo.',
    //footer
    contactUs: 'Contacta-nos',
    rightsReserved: '© Movieverse 2019. Todos os direitos reservados.',
    //movie search
    movieSearch: 'Pesquisa de Filmes',
    genres: 'Categorias',
    sortBy: 'Ordenar por',
    dateAsc: 'Data (Ascendente)',
    dateDesc: 'Data (Descendente)',
    rating: 'Classificação',
    popular: 'Popular',
    upcoming: 'Em breve',
    showMore: 'Mostrar mais',
    //genres
    Action: '🔥 Ação',
    Adventure: '🗺️ Aventura',
    Animation: '🐭 Animação',
    Comedy: '😂 Comédia',
    Crime: '👮 Crime',
    Documentary: '💡 Documentário',
    Drama: '🎭 Drama',
    Family: '👪 Família',
    Fantasy: '🗡️ Fantasia',
    History: '📜 História',
    Horror: '👻 Terror',
    Music: '🎵 Música',
    Mystery: '🕵️‍ Mistério',
    Romance: '❤️ Romance',
    'Science Fiction': '🤖 Ficção Científica',
    'TV Movie': '📺 Filme para TV',
    Thriller: '🔪 Thriller',
    War: '⚔️ Guerra',
    Western: '🤠 Western',
    None: 'Nenhum',
    //showtimes
    showtimes: 'Em exibição',
    //people search
    peopleSearch: 'Pesquisa membros de elenco e staff',
    bornToday: 'Nascidos hoje',
    years: 'anos',
    peopleMostCredits: 'Pessoas com mais créditos',
    credits: 'créditos',
    //aux pages
    noResultsFound: 'Nenhuns resultados encontrados',
    loading: 'Carregando',
    noMoreResults: 'Sem mais resultados',
    toTheMainPage: 'Para a página principal!',
    pageNotFound: '404 - Página não encontrada',
    noAuth: 'Precisa de estar autenticado para aceder a esta página',
    //profile
    favouriteGenre: 'Categoria Favorita',
    birthdate: 'Nascimento',
    joined: 'Criação',
    hours: 'Horas',
    ratings: 'Classifcações',
    friends: 'Amigos',
    recent: 'Recentes',
    favourites: 'Favoritos',
    watchlist: 'Para ver',
    recommended: 'Recomendados',
    noFriends: 'Sem amigos',
    confirm: 'Confirmar',
    cancel: 'Cancelar',
    changeAvatar: 'Alterar avatar',
    dragImage: 'Arraste uma imagem ou clique aqui para selecionar',
    //find users
    findUsers: 'Encontrar utilizadores',
    usernameRealName: 'Nome de utilizador/real',
    userMightKnow: 'Utilzadores que pode conhecer',
    mostUpvoted: 'Mais votados',
    likes: 'Gostos',
    //friends requests
    friendsRequests: 'Pedidos de amizade',
    received: 'Recebido',
    sent: 'Enviado',
    reject: 'Rejeitar',
    rejected: 'Rejeitado',
    accept: 'Aceitar',
    accepted: 'Aceitado',
    canceled: 'Cancelado',
    friendsInCommon: 'amigos em comum',
    requestFrom: 'Pedido de',
    requestTo: 'Pedido para',
    // movie page
    markWatched: 'Marcar visto',
    markedWatched: 'Visto!',
    addToFavourites: 'Adicionar aos favoritos',
    addedToFavourites: 'Adicionado aos favoritos!',
    addToWatchlist: 'Adicionar à watchlist',
    addedToWatchlist: 'Adicionado à watchlist!',
    originalLanguage: 'Língua original',
    runtime: 'Duração',
    genres: 'Géneros',
    prodCompanies: 'Produtoras',
    summary: 'Sumário',
    cast: 'Elenco',
    media: 'Media',
    posters: 'Posters',
    videos: 'Vídeos',
    backdrops: 'Backdrops',
    discussion: 'Discussão',
    addComment: 'Adicionar comentário',
    addCommentPlaceholder: 'Adicione um comentário...',
    //admin
    globalStats: 'Estatísticas Globais',
    genders: 'Sexos',
    countries: 'Países',
    timeRange: 'Intervalo de Tempo',
    updateInterval: 'Taxa de Atualização',
    second: 'segundo',
    seconds: 'segundos',
    minute: 'minuto',
    minutes: 'minutos',
    hour: 'hora',
    hours: 'horas',
    day: 'dia',
    week: 'semana',
    weeks: 'semanas',
    month: 'mês',
    months: 'meses',
    year: 'ano'
  }
}


////////////////

export const selectStyles = {
  control: (base, state) => ({
    ...base,
    background: "#e9e9e9",
    minHeight: '36px',
    fontFamily: 'Roboto',
    marginBottom: '10px',
    hover:  {
      cursor: 'pointer'
    }
    
  }),
  menu: base => ({
    ...base,
    borderRadius: 0,
    marginTop: 0,
  }),
  menuList: base => ({
    ...base,
    fontFamily: 'Roboto',
    padding: 0
  }),
  clearIndicator: base => ({
    ...base,
    padding: 4
  }),
  valueContainer: base => ({
    ...base,
    padding: '0px 10px',
  }),
  input: base => ({
    ...base,
    margin: 0,
    padding: 0
  }),
  multiValue: (styles, { data }) => {
    return {
      ...styles,
      backgroundColor: '#d0d0d0',
      marginRight: '5px'
    };
  },
  multiValueLabel: (styles, { data }) => ({
    ...styles,
    color: data.color,
  }),
  multiValueRemove: (styles, { data }) => ({
    ...styles,
    color: data.color,
    ':hover': {
      backgroundColor: data.color,
      color: 'red',
    },
  }),
};